### PR TITLE
add executable bit to gradlew

### PR DESCRIPTION
**Pull request by CyberFlameGO**
removes chmod from workflow

### CODE REVIEW

**Comment by IMS212** [comment]
why do you even-

**Comment by CyberFlameGO** [comment]
Multiple branches, multiple PRs

**Comment by LizIsTired** [comment]
Can you close this PR please?

**Comment by CyberFlameGO** [comment]
Uh why? It’s a useful contribution imo because people less experienced with gradle and chmod probably won’t understand the error they get when they try to run `./gradlew build`

**Comment by CyberFlameGO** [comment]
Just noticed that you had a more descriptive comment in #30 so I’ll explain why I made multiple there

**Pull request closed without merging**
